### ISSUE TITLE
Mark Conversation

### ISSUE THREAD

**Issue by rubenlagus** [rubenlagus/Tsupport#4]
Mark conversation feature will be added with 3 kind of marks:

1. **Local mark:** Only available in that device.
2. **Private mark:** Available in other device using same number (only Android devices).
3. **Global mark:** Will appear to all people in the same Support group... as a shared marked conversation.

**Comment by moshmo** [comment]
How can sign in to this app?

**Comment by moshmo** [comment]
Please

**Comment by moshmo** [comment]
Please let me know how to sign on

**Comment by rubenlagus** [comment]
@moshmo Sorry but this is not a general app, you need to be part of Telegram Support Initiative to be able to use it.
